### ISSUE TITLE
Czar clicking X makes the 2nd white card stay up there.

### ISSUE THREAD

**Issue by schmidtec** [falkrons/HaH#16] opened 2016-05-17 18:52 UTC
Czar, selecting a white card, clicking X, putting the card back, picking the other one and clicking ✓. What happened was the 2nd card that I did pick, stayed up there throughout further game play. I played a game after and the card was still up there, getting in the way of the next white card that went up there.

**Comment by schmidtec** [comment] 2016-05-18 01:28
Falkrons and I reproduced this.

Also, when that card is stuck up there and the next round is played, the next white card gets selected, is covered by the old card, ✓ is clicked, the old stuck card goes away, but is replaced by the latest selected white card which then gets stuck as well.

**Comment by stevenvergenz** [comment] 2016-05-18 12:02
Sounds like an unhandled exception. Anything in the console? And does it get stuck for all players, or just the czar?

**Comment by schmidtec** [comment] 2016-05-23 19:06
It gets stuck for ALL players.

Here is the console after me playing a round and trying to repro this error:

THREE.AltRenderer 73
AltRenderer version 0.2.0
["init", Array[0], "roundFinished", null, null, null]
 game.js:54
New player joined: Guest7170891 game.js:190
["playerJoin", "413315319583474534", "Guest7170891", Array[1]]
 game.js:54
New player joined: CHAPPiE game.js:190
["playerJoin", "99229457465737419", "CHAPPiE", Array[2]]
 game.js:54
New player joined: schmidtec game.js:190
["playerJoin", "63706211886826413", "schmidtec", Array[3]]
 game.js:54
["dealCards", Array[10], Object, "413315319583474534"]
 game.js:54
["dealCards", 10, Object, "413315319583474534"]
 game.js:54
blackCard scale 
THREE.Vector3 {x: 2, y: 2, z: 2, constructor: function, set: function…}
 game.js:444
["roundStart"] game.js:54
["cardSelection", Array[1], "63706211886826413"]
 game.js:54
naming something czarStack game.js:589
["cardSelection", Array[1], "99229457465737419"]
 game.js:54
["cardSelectionComplete", Object]
 game.js:54
naming something czarStack game.js:589
["presentSubmission", "63706211886826413"] game.js:54
["presentSubmission", ""] game.js:54
["presentSubmission", "63706211886826413"] game.js:54
["presentSubmission", ""] game.js:54
["presentSubmission", "99229457465737419"] game.js:54
["winnerSelection", "99229457465737419"] game.js:54
AltspaceVR: 158 has left the composition's boundaries and will be hidden until it returns. (This message will not be shown again for this object until the app is reloaded)
AltspaceVR: 161 has left the composition's boundaries and will be hidden until it returns. (This message will not be shown again for this object until the app is reloaded)
AltspaceVR: 160 has left the composition's boundaries and will be hidden until it returns. (This message will not be shown again for this object until the app is reloaded)
AltspaceVR: 159 has left the composition's boundaries and will be hidden until it returns. (This message will not be shown again for this object until the app is reloaded)

**Comment by stevenvergenz** [comment] 2016-05-31 12:20
Interestingly, this seems to happen to regular players too. Select a card, hit the X, and select another card. The second card will stay after you submit it.

**Comment by stevenvergenz** [comment] 2016-05-31 18:24
Seems to be fixed as of 490aece. Can't reproduce original bug for czar, but the player stuck card is fixed.

**Closed as completed** 2016-05-31 18:27 UTC
Labels: bug
